In [13]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv("Results/20221118.csv")

In [15]:
before_drop = pd.read_csv("Results/20221118_before_drop.csv")

In [16]:
data.drop(["Unnamed: 0"],axis=1, inplace=True)

In [17]:
data = pd.get_dummies(data, columns=['설계안정성검토','공공민간구분'])

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14289 entries, 0 to 14288
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   날씨             14289 non-null  object
 1   온도             14289 non-null  float64
 2   시설물 분류         14289 non-null  object
 3   작업프로세스         14289 non-null  object
 4   사망자            14289 non-null  int64
 5   20이상 30미만 사망자  14289 non-null  int64
 6   30이상 40미만 사망자  14289 non-null  int64
 7   40이상 50미만 사망자  14289 non-null  int64
 8   50이상 60미만 사망자  14289 non-null  int64
 9   60이상 사망자       14289 non-null  int64
 10  부상자            14289 non-null  int64
 11  20이상 30미만 부상자  14289 non-null  int64
 12  30이상 40미만 부상자  14289 non-null  int64
 13  40이상 50미만 부상자  14289 non-null  int64
 14  50이상 60미만 부상자  14289 non-null  int64
 15  60이상 부상자       14289 non-null  int64
 16  공정율            14289 non-null  object
 17  Month          14289 non-null  float64
 18  Time           14289 non-null  float64
 19  사고종류           14289 non-null  object
 20  공종             14289 non-null  object
 21  공사규모_0-5       14289 non-null  float64
 22  공사규모_5-10      14289 non-null  float64
 23  공사규모_10-30     14289 non-null  float64
 24  공사규모_30-50     14289 non-null  float64
 25  공사규모_50-100    14289 non-null  float64
 26  공사규모_100-500   14289 non-null  float64
 27  공사규모_500-1000  14289 non-null  float64
 28  공사규모_1000-     14289 non-null  float64
 29  공사기간           14289 non-null  float64
 30  설계안정성검토_대상     14289 non-null  uint8
 31  설계안정성검토_미입력    14289 non-null  uint8
 32  설계안정성검토_비대상    14289 non-null  uint8
 33  공공민간구분_공공      14289 non-null  uint8
 34  공공민간구분_미입력     14289 non-null  uint8
 35  공공민간구분_민간      14289 non-null  uint8
dtypes: float64(12), int64(12), object(6), uint8(6)
memory usage: 3.4+ MB

In [19]:
(data['사망자']+data['부상자']).value_counts()

1     14001
2       142
0        91
3        29
4        15
5         6
7         2
48        1
6         1
17        1
dtype: int64

In [20]:
temp = data.copy()

In [21]:
temp.drop(['20이상 30미만 사망자','30이상 40미만 사망자','40이상 50미만 사망자','50이상 60미만 사망자','60이상 사망자'],axis=1,inplace=True)

In [22]:
temp.drop(['20이상 30미만 부상자','30이상 40미만 부상자','40이상 50미만 부상자','50이상 60미만 부상자','60이상 부상자'],axis=1,inplace=True)

In [23]:
temp['날씨'].value_counts()

맑음    10733
흐림     2650
강우      670
안개      148
강설       56
강풍       32
Name: 날씨, dtype: int64

In [24]:
temp = pd.get_dummies(temp, columns=['날씨'])

In [25]:
temp['공종'].value_counts()

콘크리트공사         3959
기타공사           1804
가설공사           1586
설비공사           1092
토공사            1032
철골공사            707
해체 및 재활용공사      695
토목공사            567
관공사             481
수장공사            363
타일 및 테라코타공사     325
미장공사            315
내외벽공사           312
도장공사            196
목공사             173
조적공사            172
지정 및 기초공사       172
금속공사            129
방수 및 방습공사       110
지붕 및 홈통공사        99
Name: 공종, dtype: int64

In [26]:
def transform_working_type(x):
    if x == '콘크리트공사':
        return 50.33
    elif x == '기타공사':
        return 17.62
    elif x == '가설공사' :
        return 24.58
    elif x == '설비공사' : #설비공사 : 건물을 지을 때 생활에 밀접한 시설을 설치하는 필수 공사로 기초공사에서 예상한 구조를 완성시키는 과정
        return 34.04
    elif x == '토공사' :
        return 18.62
    elif x == '철골공사' :
        return 38.11
    elif x == '해체 및 재활용공사' :
        return 20.09
    elif x == '토목공사' : #일단 콘크리트로 ... 이거 어케해요ㅠ
        return 50.33
    elif x == '관공사' :
        return 17.62 # 기타로...
    elif x == '수장공사' :
        return 6.71
    elif x == '타일 및 테라코타공사' :
        return 18.18
    elif x == '미장공사' :
        return 32.36
    elif x == '내외벽공사' :
        return 32.83
    elif x == '도장공사' :
        return 18.90
    elif x == '목공사' :
        return 4.21
    elif x == '조적공사' :
        return 14.79
    elif x == '지정 및 기초공사' :
        return 34.04
    elif x == '금속공사' :
        return 8.54
    elif x == '방수 및 방습공사' :
        return 21.11
    elif x == '지붕 및 홈통공사' :
        return 85.64

In [27]:
temp['공종'] = temp['공종'].apply(transform_working_type)

In [28]:
def transform_temperature(x):
    if x < 0:
        return 0.196
    elif x>=0 and x < 4:
        return 0.163
    elif x>=4 and x<8:
        return 0.109
    elif x>=8 and x <12:
        return 0.082
    elif x>=12 and x<16:
        return 0.054
    elif x>=16 and x<20:
        return 0.043
    elif x >=20 and x<24:
        return 0.101
    elif x>=24 and x<28:
        return 0.125
    elif x>= 28:
        return 0.128

In [29]:
temp['온도'] = temp['온도'].apply(transform_temperature)

In [30]:
temp['공정율'].value_counts()

90% 이상    2215
20~29%    1527
10~19%    1512
30~39%    1500
80~89%    1322
40~49%    1318
50~59%    1304
10% 미만    1229
70~79%    1218
60~69%    1144
Name: 공정율, dtype: int64

In [31]:
def transform_working_per(x):
    if x =='90% 이상':
        return 0.1
    elif x=='20~29%':
        return 0.124
    elif x=='10~19%':
        return 0.092
    elif x=='10% 미만':
        return 0.083
    elif x=='30~39%':
        return 0.111
    elif x=='40~49%':
        return 0.085
    elif x=='50~59%':
        return 0.099
    elif x=='60~69%':
        return 0.111
    elif x=='70~79%':
        return 0.088
    elif x=='80~89%':
        return 0.107

In [32]:
temp['공정율'] = temp['공정율'].apply(transform_working_per)

In [33]:
def transform_month(x):
    if x==1:
        return 0.068
    elif x==2:
        return 0.086
    elif x==3:
        return 0.173
    elif x==4:
        return 0.068
    elif x==5:
        return 0.08
    elif x==6:
        return 0.086
    elif x==7:
        return 0.080
    elif x==8:
        return 0.111
    elif x==9:
        return 0.049
    elif x==10:
        return 0.086
    elif x==11:
        return 0.056
    elif x==12:
        return 0.056

In [34]:
temp['Month'] = temp['Month'].apply(transform_month)

In [35]:
temp

,온도,시설물 분류,작업프로세스,사망자,부상자,공정율,Month,Time,사고종류,공종,...,설계안정성검토_비대상,공공민간구분_공공,공공민간구분_미입력,공공민간구분_민간,날씨_강설,날씨_강우,날씨_강풍,날씨_맑음,날씨_안개,날씨_흐림
0,0.101,기타 건축,해체작업,0,1,0.124,0.080,7.0,끼임,17.62,...,1,0,0,1,0,0,0,1,0,0
1,0.128,공동주택,해체작업,0,1,0.107,0.080,8.0,물체에 맞음,24.58,...,1,0,0,1,0,1,0,0,0,0
2,0.128,토목,해체작업,0,1,0.111,0.080,9.0,떨어짐,24.58,...,1,0,0,1,0,0,0,1,0,0
3,0.101,토목,해체작업,0,1,0.100,0.080,10.0,"절단, 베임",24.58,...,0,1,0,0,0,0,0,1,0,0
4,0.125,공동주택,설비작업,0,1,0.099,0.080,10.0,넘어짐,34.04,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14284,0.101,기타 건축,마감작업,0,1,0.107,0.086,9.0,떨어짐,32.36,...,1,0,0,1,0,0,0,1,0,0
14285,0.101,기타 건축,해체작업,0,1,0.124,0.086,14.0,부딪힘,50.33,...,0,1,0,0,0,0,0,1,0,0
14286,0.054,토목,조립작업,0,1,0.111,0.086,9.0,끼임,50.33,...,1,1,0,0,0,0,0,0,0,1
14287,0.054,기타 건축,설치작업,0,1,0.111,0.086,9.0,떨어짐,18.18,...,1,0,0,1,0,0,0,1,0,0
14288,0.054,기타 건축,이동,0,1,0.092,0.086,7.0,떨어짐,24.58,...,1,0,0,1,0,0,0,1,0,0

In [36]:
# 작업프로세스, Time, 사고종류, 공사규모, 미입력 처리

In [37]:
temp['공사규모_0-5'] = temp['공사규모_0-5'].apply(lambda x: 0.139 if x==1.0 else 0)

In [38]:
temp['공사규모_5-10'] = temp['공사규모_5-10'].apply(lambda x: 0.174 if x==1.0 else 0)

In [39]:
temp['공사규모_10-30'] = temp['공사규모_10-30'].apply(lambda x: 0.132 if x==1.0 else 0)

In [40]:
temp['공사규모_30-50'] = temp['공사규모_30-50'].apply(lambda x: 0.143 if x==1.0 else 0)

In [41]:
temp['공사규모_50-100'] = temp['공사규모_50-100'].apply(lambda x: 0.116 if x==1.0 else 0)

In [42]:
temp['공사규모_100-500'] = temp['공사규모_100-500'].apply(lambda x: 0.084 if x==1.0 else 0)

In [43]:
temp['공사규모_500-1000'] = temp['공사규모_500-1000'].apply(lambda x: 0.114 if x==1.0 else 0)

In [44]:
temp['공사규모_1000-'] = temp['공사규모_1000-'].apply(lambda x: 0.098 if x==1.0 else 0)

In [45]:
test = temp['공사규모_0-5']+temp['공사규모_5-10']+temp['공사규모_10-30']+temp['공사규모_30-50']+temp['공사규모_50-100']+temp['공사규모_100-500']+temp['공사규모_500-1000']+temp['공사규모_1000-']

In [46]:
temp['공사규모'] = test

In [47]:
temp.drop(['공사규모_0-5','공사규모_5-10','공사규모_10-30','공사규모_30-50','공사규모_50-100','공사규모_100-500','공사규모_500-1000','공사규모_1000-'],axis=1, inplace=True)

In [48]:
temp['사고종류'].value_counts()

넘어짐       3368
떨어짐       2801
물체에 맞음    2201
끼임        1558
기타        1404
절단, 베임    1016
부딪힘        949
깔림         302
질병         190
찔림         170
화상          95
교통사고        74
전도          41
감전          34
화재          29
충돌          14
질식          13
붕괴          12
탈락           6
파열, 파단       6
낙하           4
폭발           2
Name: 사고종류, dtype: int64

In [49]:
temp['시설물 분류'].value_counts()

기타 건축     5272
공동주택      4117
토목        2993
공장        1152
산업환경설비     619
조경         136
Name: 시설물 분류, dtype: int64

In [50]:
temp = pd.get_dummies(temp, columns=['시설물 분류'])

In [51]:
temp['작업프로세스'].value_counts()

설치작업         2491
해체작업         1544
이동           1504
운반작업         1219
정리작업          938
기타            828
조립작업          700
형틀 및 목공       560
마감작업          478
타설작업          456
절단작업          414
준비작업          340
설비작업          238
도장작업          199
청소작업          185
용접작업          167
상차 및 하역작업     165
연결작업          164
굴착작업          157
인양작업          145
미입력           138
확인 및 점검작업     115
쌓기작업          104
보수 및 교체작업     101
매설작업           98
천공작업           97
양중작업           85
정비작업           82
부설 및 다짐작업      79
전기작업           78
벌목작업           65
항타 및 항발작업      59
거치작업           58
반출작업           54
적재작업           46
고소작업           31
물뿌리기 작업        27
양생작업           20
측량작업           20
절취작업           17
장약 및 발파작업      14
인발작업            9
Name: 작업프로세스, dtype: int64

In [52]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14289 entries, 0 to 14288
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   온도             14289 non-null  float64
 1   작업프로세스         14289 non-null  object
 2   사망자            14289 non-null  int64
 3   부상자            14289 non-null  int64
 4   공정율            14289 non-null  float64
 5   Month          14289 non-null  float64
 6   Time           14289 non-null  float64
 7   사고종류           14289 non-null  object
 8   공종             14289 non-null  float64
 9   공사기간           14289 non-null  float64
 10  설계안정성검토_대상     14289 non-null  uint8
 11  설계안정성검토_미입력    14289 non-null  uint8
 12  설계안정성검토_비대상    14289 non-null  uint8
 13  공공민간구분_공공      14289 non-null  uint8
 14  공공민간구분_미입력     14289 non-null  uint8
 15  공공민간구분_민간      14289 non-null  uint8
 16  날씨_강설          14289 non-null  uint8
 17  날씨_강우          14289 non-null  uint8
 18  날씨_강풍          14289 non-null  uint8
 19  날씨_맑음          14289 non-null  uint8
 20  날씨_안개          14289 non-null  uint8
 21  날씨_흐림          14289 non-null  uint8
 22  공사규모           14289 non-null  float64
 23  시설물 분류_공동주택    14289 non-null  uint8
 24  시설물 분류_공장      14289 non-null  uint8
 25  시설물 분류_기타 건축   14289 non-null  uint8
 26  시설물 분류_산업환경설비  14289 non-null  uint8
 27  시설물 분류_조경      14289 non-null  uint8
 28  시설물 분류_토목      14289 non-null  uint8
dtypes: float64(7), int64(2), object(2), uint8(18)
memory usage: 1.4+ MB

In [53]:
test = temp.copy()

In [54]:
test

,온도,작업프로세스,사망자,부상자,공정율,Month,Time,사고종류,공종,공사기간,...,날씨_맑음,날씨_안개,날씨_흐림,공사규모,시설물 분류_공동주택,시설물 분류_공장,시설물 분류_기타 건축,시설물 분류_산업환경설비,시설물 분류_조경,시설물 분류_토목
0,0.101,해체작업,0,1,0.124,0.080,7.0,끼임,17.62,744.0,...,1,0,0,0.132,0,0,1,0,0,0
1,0.128,해체작업,0,1,0.107,0.080,8.0,물체에 맞음,24.58,1.0,...,0,0,0,0.084,1,0,0,0,0,0
2,0.128,해체작업,0,1,0.111,0.080,9.0,떨어짐,24.58,244.0,...,1,0,0,0.098,0,0,0,0,0,1
3,0.101,해체작업,0,1,0.100,0.080,10.0,"절단, 베임",24.58,1565.0,...,1,0,0,0.114,0,0,0,0,0,1
4,0.125,설비작업,0,1,0.099,0.080,10.0,넘어짐,34.04,882.0,...,1,0,0,0.114,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14284,0.101,마감작업,0,1,0.107,0.086,9.0,떨어짐,32.36,44.0,...,1,0,0,0.143,0,0,1,0,0,0
14285,0.101,해체작업,0,1,0.124,0.086,14.0,부딪힘,50.33,182.0,...,1,0,0,0.143,0,0,1,0,0,0
14286,0.054,조립작업,0,1,0.111,0.086,9.0,끼임,50.33,70.0,...,0,0,1,0.114,0,0,0,0,0,1
14287,0.054,설치작업,0,1,0.111,0.086,9.0,떨어짐,18.18,31.0,...,1,0,0,0.174,0,0,1,0,0,0
14288,0.054,이동,0,1,0.092,0.086,7.0,떨어짐,24.58,244.0,...,1,0,0,0.084,0,0,1,0,0,0

In [55]:
y_data = test['사망자']

In [56]:
test.drop(['작업프로세스','사망자','부상자','사고종류','Time'],axis=1, inplace=True)

In [57]:
# 작업 프로세스 - 너무 많음....이를 어찌하면 좋을까...
# 사고 종류 - 이것도 어느정도 합치는게 좋을 것 같음
# Time - 시간을 어떻게 나눌까 임의로 걍 나눠버려?
# Label data가 무엇이 될지 생각좀 해야할 듯

In [58]:
test.drop(['설계안정성검토_미입력','공공민간구분_미입력'],axis=1, inplace=True)

In [59]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14289 entries, 0 to 14288
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   온도             14289 non-null  float64
 1   공정율            14289 non-null  float64
 2   Month          14289 non-null  float64
 3   공종             14289 non-null  float64
 4   공사기간           14289 non-null  float64
 5   설계안정성검토_대상     14289 non-null  uint8
 6   설계안정성검토_비대상    14289 non-null  uint8
 7   공공민간구분_공공      14289 non-null  uint8
 8   공공민간구분_민간      14289 non-null  uint8
 9   날씨_강설          14289 non-null  uint8
 10  날씨_강우          14289 non-null  uint8
 11  날씨_강풍          14289 non-null  uint8
 12  날씨_맑음          14289 non-null  uint8
 13  날씨_안개          14289 non-null  uint8
 14  날씨_흐림          14289 non-null  uint8
 15  공사규모           14289 non-null  float64
 16  시설물 분류_공동주택    14289 non-null  uint8
 17  시설물 분류_공장      14289 non-null  uint8
 18  시설물 분류_기타 건축   14289 non-null  uint8
 19  시설물 분류_산업환경설비  14289 non-null  uint8
 20  시설물 분류_조경      14289 non-null  uint8
 21  시설물 분류_토목      14289 non-null  uint8
dtypes: float64(6), uint8(16)
memory usage: 893.2 KB

In [60]:
test

,온도,공정율,Month,공종,공사기간,설계안정성검토_대상,설계안정성검토_비대상,공공민간구분_공공,공공민간구분_민간,날씨_강설,...,날씨_맑음,날씨_안개,날씨_흐림,공사규모,시설물 분류_공동주택,시설물 분류_공장,시설물 분류_기타 건축,시설물 분류_산업환경설비,시설물 분류_조경,시설물 분류_토목
0,0.101,0.124,0.080,17.62,744.0,0,1,0,1,0,...,1,0,0,0.132,0,0,1,0,0,0
1,0.128,0.107,0.080,24.58,1.0,0,1,0,1,0,...,0,0,0,0.084,1,0,0,0,0,0
2,0.128,0.111,0.080,24.58,244.0,0,1,0,1,0,...,1,0,0,0.098,0,0,0,0,0,1
3,0.101,0.100,0.080,24.58,1565.0,1,0,1,0,0,...,1,0,0,0.114,0,0,0,0,0,1
4,0.125,0.099,0.080,34.04,882.0,1,0,0,1,0,...,1,0,0,0.114,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14284,0.101,0.107,0.086,32.36,44.0,0,1,0,1,0,...,1,0,0,0.143,0,0,1,0,0,0
14285,0.101,0.124,0.086,50.33,182.0,1,0,1,0,0,...,1,0,0,0.143,0,0,1,0,0,0
14286,0.054,0.111,0.086,50.33,70.0,0,1,1,0,0,...,0,0,1,0.114,0,0,0,0,0,1
14287,0.054,0.111,0.086,18.18,31.0,0,1,0,1,0,...,1,0,0,0.174,0,0,1,0,0,0
14288,0.054,0.092,0.086,24.58,244.0,0,1,0,1,0,...,1,0,0,0.084,0,0,1,0,0,0

In [61]:
from sklearn.preprocessing import MinMaxScaler

In [62]:
scaler = MinMaxScaler()

scaler.fit(test)
test_scaled = scaler.transform(test)
test_scaled = pd.DataFrame(data = test_scaled)

In [63]:
test_scaled

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.379085,1.000000,0.250000,0.164681,0.108779,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.533333,0.0,0.0,1.0,0.0,0.0,0.0
1,0.555556,0.585366,0.250000,0.250154,0.035900,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.0
2,0.555556,0.682927,0.250000,0.250154,0.059735,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.155556,0.0,0.0,0.0,0.0,0.0,1.0
3,0.379085,0.414634,0.250000,0.250154,0.189308,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,1.0
4,0.535948,0.390244,0.250000,0.366327,0.122315,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.333333,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14284,0.379085,0.585366,0.298387,0.345696,0.040118,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.655556,0.0,0.0,1.0,0.0,0.0,0.0
14285,0.379085,1.000000,0.298387,0.566376,0.053654,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.655556,0.0,0.0,1.0,0.0,0.0,0.0
14286,0.071895,0.682927,0.298387,0.566376,0.042668,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.333333,0.0,0.0,0.0,0.0,0.0,1.0
14287,0.071895,0.682927,0.298387,0.171558,0.038843,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.000000,0.0,0.0,1.0,0.0,0.0,0.0
14288,0.071895,0.219512,0.298387,0.250154,0.059735,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0

In [64]:
from sklearn import model_selection
from sklearn.metrics import accuracy_score

import joblib

import warnings
warnings.filterwarnings("ignore")

In [65]:
X_data = test_scaled
Y_data = np.array(y_data)

x_train, x_test, y_train, y_test = model_selection.train_test_split(X_data, Y_data, test_size=0.3, random_state=0)

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import cross_val_score

In [67]:
models = [
    ('Logistic', LogisticRegression()),
    ('KNN', KNeighborsClassifier(16)),
    ('SVM', SVC(kernel='rbf', C=100, gamma=0.01)),
    ('DecisionTree', DecisionTreeClassifier(random_state = 0, max_depth = 4)),
    ('RandomForest', RandomForestClassifier(random_state = 0, n_estimators = 100, max_depth = 6)),
    ('NaiveBayes', BernoulliNB(alpha=10))
]

In [68]:
from sklearn.metrics import classification_report

In [71]:
from sklearn import metrics

In [73]:
for name, model in models:
    model.fit(x_train, y_train)
    print(f'{name} _accuracy: ', metrics.accuracy_score(model.predict(x_test), y_test))
    print(f'{name} _precision: ', metrics.precision_score(model.predict(x_test), y_test,average='micro'))
    print(f'{name} _recall: ', metrics.recall_score(model.predict(x_test), y_test,average='micro'))
    print(f'{name} _f1 score: ', metrics.f1_score(model.predict(x_test), y_test,average='micro'))
    print(" ")

Logistic _accuracy:  0.9538138558432471
Logistic _precision:  0.9538138558432471
Logistic _recall:  0.9538138558432471
Logistic _f1 score:  0.9538138558432472

KNN _accuracy:  0.9538138558432471
KNN _precision:  0.9538138558432471
KNN _recall:  0.9538138558432471
KNN _f1 score:  0.9538138558432472

SVM _accuracy:  0.9538138558432471
SVM _precision:  0.9538138558432471
SVM _recall:  0.9538138558432471
SVM _f1 score:  0.9538138558432472

DecisionTree _accuracy:  0.9526475390716118
DecisionTree _precision:  0.9526475390716118
DecisionTree _recall:  0.9526475390716118
DecisionTree _f1 score:  0.9526475390716118

RandomForest _accuracy:  0.9538138558432471
RandomForest _precision:  0.9538138558432471
RandomForest _recall:  0.9538138558432471
RandomForest _f1 score:  0.9538138558432472

NaiveBayes _accuracy:  0.95358059248892
NaiveBayes _precision:  0.95358059248892
NaiveBayes _recall:  0.95358059248892
NaiveBayes _f1 score:  0.95358059248892